---
title: "Metrics"
author: "Sixtus Dakurah"
date: "11/22/2020"
output: pdf_document
---


```{r setup, include=FALSE}
rm(list = ls()) # clear environment
knitr::opts_chunk$set(echo = TRUE)
# load packages
library(liger)
library(Matrix)
library(patchwork)
```


## Load and Process Data

```{r}
original_clusters <- read.csv("clusters.csv")
head(original_clusters)
liger_clusters <- read.csv("clusters-liger.csv")
head(liger_clusters)
neumf_clusters <- read.csv("clusters-neumf.csv")
head(neumf_clusters)
```


# Create better labelling by selecting only cells present in the clustering

```{r}
# create new frame
df <- data.frame("cell"  = liger_clusters$a2)
K <- dim(df)[1]
originalCells <- original_clusters$X
df$cluster <- rep(-1, K)
for (k in 1:K){
  cell <- df[k, 1]
  if (cell %in% originalCells)  df[k, 2] = original_clusters[which(original_clusters$X==cell), 2]
}
head(df)
```

# The data do not have many common cells

```{r}
intersect(original_clusters$X, neumf_clusters$a2)
```

# Read in Meilan's data and check

```{r}
dat.m1 <- read.table("pbmc_alignment/pbmc_10X.expressionMatrix.txt")
dat.m2 <- read.table("pbmc_alignment/pbmc_SeqWell.expressionMatrix.txt")
```

```{r}
head(dat.m1)
```


```{r}
write.csv(dat.m1, file = "pbmc_10X.csv")
write.csv(dat.m2, file = "pbmc_SqW.csv")
```


```{r}
dat2.0 <- readRDS("data/PBMC_control.rds")
```

```{r}
head(dat.m)
dim(dat.m)
dim(dat2.0)
```


```{r}
# collect column names
cells.m <- colnames(dat.m)
length(cells.m)
```

```{r}
print(paste("Unique cells in data with true clusters: ", length(unique(original_clusters$X))))
print(paste("Unique cells in data used for liger and neumf: ", length(unique(liger_clusters$a2))))
print(paste("Unique cells from 10x data: ", length(unique(cells.m))))
```

```{r}
length(intersect(liger_clusters$X, cells.m))
```

### They are no common cells between the two datasets.


### Check if the genes agree

```{r}
genes.m <- rownames(dat.m)
length(unique(genes.m))
```


```{r}
ctrl_dge <- RDS_from_web("https://sixtusdakurah.com/projects/liger/ctrl_dge.rds") # original PBMC data
genes.or1 <- ctrl_dge$X

stim_dge <- RDS_from_web("https://sixtusdakurah.com/projects/liger/stim_dge.rds") # original PBMC data
genes.or2 <- stim_dge$X

length(unique(genes.or2)) 
length(unique(genes.or1))
```

```{r}
length(intersect(c(genes.or1, genes.or2), genes.m))
```

## They only have this number of genes in common.





